/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: isabm (https://sketchfab.com/isabm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hildas-fox-e28e66929cb74ea8a28d7471387424e9
Title: 🦋 Hilda's Fox 🦊
*/

import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import foxIslandScene from '../assets/3d/foxbg.glb'
import { a } from '@react-spring/three'


const FoxIsland = (props) => {
  const foxislandRef = useRef();
  const { nodes, materials } = useGLTF(foxIslandScene)
  return (
   
      <a.group ref={foxislandRef} {...props} >

        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Hierba}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Hierba}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.grass}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.water}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Rocks_1}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Rocks_2}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.SHINE}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Tree}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.Tree_2}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.WINGS}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.WINGS}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.seta}
        />
      </a.group>

  )
}

export default FoxIsland;
